language: node_js
 - "7"

sudo: required
dist: trusty

before_script:
  - npm install -g gulp-cli

script:
  - sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
  - npm install
  - bash tools/travis-deploy.sh
